services:
  - type: web
    name: telegram-upload-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: 8844239608:AAHszuQ2AFaAW3T5l2rU8XuHyBFsNq7asPA
        sync: false
